tusur:
  title: 'Официальный сайт университета'
  link: 'https://tusur.ru'

phones:
  title: 'Телефонный справочник'
  link: 'https://directory.tusur.ru'

abiturient:
  title: 'Абитуриентам'
  link: 'https://abiturient.tusur.ru'


